services:
  backend:
    container_name: backend
    image: mehboobpatel/funbackend:latest
    ports:
      - "3000:3000"
    command: sh -c "node dist/apps/backend/main.js"
    depends_on:
      - migrations
    env_file:
      - .env
    networks:
      - app-network

  currency:
    container_name: currency
    image: mehboobpatel/funbackend:latest
    command: sh -c "node dist/apps/currency/main.js"
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - backend

  
  riddle:
    container_name: riddle
    image: mehboobpatel/funbackend:latest
    command: sh -c "node dist/apps/riddle/main.js"
    ports:
      - "3002:3002"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - backend

  frontend:
    container_name: frontend

    image: mehboobpatel/funfrontend:latest
    ports:
      - "8082:80"
    depends_on:
      - backend
    networks:
      - app-network

  migrations:
    container_name: test-migrations
    image: mehboobpatel/funmigrations:latest
    command: sh migrations.sh
    volumes:
      - ./infra/keys/:/home/app/decryptkey/
    env_file:
      - migrations.env

networks:
  app-network:
    driver: bridge
