FROM node:22-alpine as build
RUN apk add rsync g++ make py3-pip
WORKDIR /home/app
COPY ./infra/migration ./
RUN mkdir config && cd postgres-migrations && npm i && cd ../config-migrations && npm i
RUN cd postgres-migrations && npm run build && npm install -g .
COPY ./apps/backend/src/app/migrations ./migrations/new
