apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mehboobpatel/funbackend:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: backend-secrets
        - configMapRef:
            name: backend-config
        command: ["sh", "-c", "node dist/apps/backend/main.js"]

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: backend